"""
Fine - Python Market Data and Trading Backtesting Library

A comprehensive library for quantitative finance research and backtesting.
"""

__version__ = "0.1.0"
__author__ = "fine Team"
__license__ = "MIT"

from .providers import (
    MarketData,
    DataProvider,
    Quote,
    KLine,
    MinuteData,
    StockInfo,
    ProviderRegistry,
    create_provider,
    TencentProvider,
    SinaProvider,
    AkshareProvider,
    BaostockProvider,
    YFinanceProvider,
)

from .indicators import (
    Indicator,
    IndicatorResult,
    IndicatorRegistry,
    TechnicalIndicators,
    compute_indicators,
    MA,
    EMA,
    BBI,
    MACD,
    KDJ,
    RSI,
    BollingerBands,
    OBV,
    ATR,
    VWAP,
    DMI,
    WR,
    CCI,
    BIAS,
    DMA,
    TRIX,
    VR,
    PSY,
    CR,
    ARBR,
    SAR,
    KeltnerChannel,
    MFI,
    WilliamsAD,
    CMF,
    StochRSI,
    DonchianChannel,
    UltimateOscillator,
)

from .fee import (
    FeeRates,
    TradeFee,
    FeeCalculator,
    SHANGHAI_RATES,
    SHENZHEN_RATES,
    KECHUANG_RATES,
    ETF_RATES,
    calculate_trade_fee,
    calculate_buy_cost,
    calculate_sell_proceeds,
)

from .strategy import (
    SignalType,
    StockSignal,
    StrategyResult,
    Condition,
    PriceCondition,
    VolumeCondition,
    IndicatorCondition,
    CompositeCondition,
    ChangeCondition,
    CustomCondition,
    Strategy,
    IndicatorFilterStrategy,
    MovingAverageStrategy,
    MACDStrategy,
    RSIStrategy,
    BrickChartStrategy,
    SimpleFunctionStrategy,
    StrategyBuilder,
    EnsembleStrategy,
    StrategyRegistry,
    create_strategy,
    scan_stocks,
)

# from .strategies import (
#     list_all_strategies,
#     list_builtin_strategies,
#     list_custom_strategies,
#     load_custom_strategies,
#     get_custom_strategies,
# )

from .backtest import (
    Position,
    Trade,
    PerformanceMetrics,
    BacktestResult,
    SignalGenerator,
    RollingWindowSignalGenerator,
    StockPool,
    StaticStockPool,
    FileStockPool,
    DynamicStockPool,
    CompositeStockPool,
    Backtest,
    BacktestConfig,
    quick_backtest,
    print_backtest_result,
    export_to_csv,
    plot_backtest_result,
)

from .portfolio import (
    PortfolioManager,
    PortfolioMetrics,
    PortfolioPosition,
    PortfolioOptimizer,
    StrategyAllocation,
    AllocationMethod,
)

from .risk import (
    RiskManager,
    RiskCheckResult,
    RiskLevel,
    RiskRule,
    PositionLimit,
    TradeLimit,
    StopLossRule,
    TakeProfitRule,
    PositionLimitRule,
    TradeLimitRule,
    CashReserveRule,
)

from .cache import (
    CSVCache,
    MemoryCache,
    CacheStats,
    get_cache,
)

__all__ = [
    # providers
    "MarketData",
    "DataProvider",
    "Quote",
    "KLine",
    "MinuteData",
    "StockInfo",
    "ProviderRegistry",
    "create_provider",
    "TencentProvider",
    "SinaProvider",
    "AkshareProvider",
    "BaostockProvider",
    "YFinanceProvider",
    # indicators
    "Indicator",
    "IndicatorResult",
    "IndicatorRegistry",
    "TechnicalIndicators",
    "compute_indicators",
    "MA",
    "EMA",
    "BBI",
    "MACD",
    "KDJ",
    "RSI",
    "BollingerBands",
    "OBV",
    "ATR",
    "VWAP",
    "DMI",
    "WR",
    "CCI",
    "BIAS",
    "DMA",
    "TRIX",
    "VR",
    "PSY",
    "CR",
    "ARBR",
    "SAR",
    "KeltnerChannel",
    "MFI",
    "WilliamsAD",
    "CMF",
    "StochRSI",
    "DonchianChannel",
    "UltimateOscillator",
    # fee
    "FeeRates",
    "TradeFee",
    "FeeCalculator",
    "SHANGHAI_RATES",
    "SHENZHEN_RATES",
    "KECHUANG_RATES",
    "ETF_RATES",
    "calculate_trade_fee",
    "calculate_buy_cost",
    "calculate_sell_proceeds",
    # strategy
    "SignalType",
    "StockSignal",
    "StrategyResult",
    "Condition",
    "PriceCondition",
    "VolumeCondition",
    "IndicatorCondition",
    "CompositeCondition",
    "ChangeCondition",
    "CustomCondition",
    "Strategy",
    "IndicatorFilterStrategy",
    "MovingAverageStrategy",
    "MACDStrategy",
    "RSIStrategy",
    "SimpleFunctionStrategy",
    "StrategyBuilder",
    "EnsembleStrategy",
    "StrategyRegistry",
    "create_strategy",
    "scan_stocks",
    "list_all_strategies",
    "list_builtin_strategies",
    "list_custom_strategies",
    "load_custom_strategies",
    "get_custom_strategies",
    # backtest
    "Position",
    "Trade",
    "PerformanceMetrics",
    "BacktestResult",
    "SignalGenerator",
    "RollingWindowSignalGenerator",
    "StockPool",
    "StaticStockPool",
    "FileStockPool",
    "DynamicStockPool",
    "CompositeStockPool",
    "Backtest",
    "quick_backtest",
    "print_backtest_result",
    # portfolio
    "PortfolioManager",
    "PortfolioMetrics",
    "PortfolioPosition",
    "PortfolioOptimizer",
    "StrategyAllocation",
    "AllocationMethod",
    # risk
    "RiskManager",
    "RiskCheckResult",
    "RiskLevel",
    "RiskRule",
    "PositionLimit",
    "TradeLimit",
    "StopLossRule",
    "TakeProfitRule",
    "PositionLimitRule",
    "TradeLimitRule",
    "CashReserveRule",
    # cache
    "CSVCache",
    "MemoryCache",
    "CacheStats",
    "get_cache",
]
